CoreumFoundation/big-dipper-2.0-cosmos

.github/workflows/build.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coreumfoundation/big-dipper-2.0-cosmos/6)
=> Add hasura build step to CI

.github/workflows/build.yml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coreumfoundation/big-dipper-2.0-cosmos/9)
=> Fix cored websocket link

.github/workflows/build.yml, src/components/nav/components/networks/components/single_network/styles.ts, src/components/nav/components/networks/index.tsx, src/configs/chain_config.testnet.json, src/configs/index.ts, src/models/big_dipper_network.ts
Add testnet configuration and build `testnet` step.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/17)
=> Draft: Testnet config

packages/ui/src/screens/home/components/consensus/index.tsx
Fixed error where clicking on the proposer would redirect to a broken link.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/29)
=> Consensus block - proposer link fix

apps/web-coreum/public/locales/en/message_contents.json, packages/ui/src/components/msg/nft/send/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/37)
=> fixed NFTSend message not displaying correctly

apps/web-coreum/public/locales/en/message_contents.json, apps/web-coreum/public/locales/en/message_labels.json, packages/ui/src/components/msg/asset/nft_add_whitelist/index.tsx, packages/ui/src/components/msg/asset/nft_remove_whitelist/index.tsx, packages/ui/src/components/msg/index.ts, packages/ui/src/components/msg/utils.tsx, packages/ui/src/models/index.ts, packages/ui/src/models/msg/asset/msg_nft_add_to_whitelist.ts, packages/ui/src/models/msg/asset/msg_nft_remove_from_whitelist.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/38)
=> added add to and remove from whitelist messages

.github/workflows/build.yml
Closes: #XXXX
---
I have...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/39)
=> Add cd pipeline for big-dipper-ui redeployment

packages/ui/src/components/msg/governance/deposit_proposal/index.tsx, packages/ui/src/components/msg/governance/vote/index.tsx, packages/ui/src/screens/account_details/components/other_tokens/components/desktop/utils.tsx, packages/ui/src/screens/account_details/components/other_tokens/components/mobile/index.tsx, packages/ui/src/screens/proposal_details/components/votes/components/tabs/index.tsx, packages/ui/src/screens/transactions/styles.ts, packages/ui/src/screens/validators/components/list/components/desktop/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/41)
=> small bug fixes to improve the explorer

packages/ui/src/screens/home/components/main_info/price_chart.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/42)
=> fixed chart issue, now fetching data from graphql

.github/workflows/build.yml, .pnp.cjs, apps/web-coreum/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/47)
=> feat: add versioning for web-coreum

apps/web-coreum/package.json, packages/ui/src/components/nav/components/mobile/components/navbar/styles.ts, packages/ui/src/components/nav/components/mobile/styles.ts, packages/ui/src/components/network_selector/index.tsx, packages/ui/src/components/network_selector/styles.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/48)
=> fix: network selector on mobile screens

apps/web-coreum/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/49)
=> feat: update version of web-coreum

apps/web-coreum/package.json, packages/ui/src/screens/account_details/components/staking/components/delegations/components/mobile/index.tsx, packages/ui/src/screens/account_details/components/staking/components/delegations/components/mobile/styles.ts, packages/ui/src/screens/validator_details/components/staking/components/delegations/components/mobile/styles.ts, packages/ui/src/screens/validator_details/components/staking/components/delegations/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/51)
=> fix: mobile view for reward block on account page

apps/web-coreum/package.json, packages/ui/src/screens/validators/components/list/hooks.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/55)
=> feat: change default ordering to voting power in desc order on validators page

apps/web-coreum/package.json, packages/ui/src/screens/account_details/components/balance/index.tsx, packages/ui/src/screens/home/components/main_info/price_chart.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/57)
=> feat: update precision for prices in USD

apps/web-coreum/package.json, packages/ui/src/components/nav/components/desktop/components/action_bar/index.tsx, packages/ui/src/components/nav/components/search_bar/hooks.ts, packages/ui/src/components/nav/components/search_bar/index.tsx, packages/ui/src/components/search/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/58)
=> fix: update search functionality for blocks to prevent numbers extraction from the search string

apps/web-coreum/package.json, packages/ui/src/components/msg/utils.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/60)
=> feat: unify message types for transactions

apps/web-coreum/package.json, packages/ui/src/components/layout/index.tsx, packages/ui/src/components/tag/styles.ts, packages/ui/src/screens/account_details/components/overview/index.tsx, packages/ui/src/screens/account_details/components/overview/styles.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/61)
=> fix: styles for share modal

apps/web-coreum/package.json, packages/ui/src/components/msg/distribution/withdraw_commission/__snapshots__/index.test.tsx.snap, packages/ui/src/components/msg/distribution/withdraw_reward/__snapshots__/index.test.tsx.snap, packages/ui/src/components/msg/utils.tsx, packages/ui/src/components/nav/components/desktop/components/action_bar/__snapshots__/index.test.tsx.snap, packages/ui/src/components/nav/components/menu_items/__snapshots__/index.test.tsx.snap, packages/ui/src/components/transactions_list/components/desktop/index.tsx, packages/ui/src/components/transactions_list_details/components/list/index.tsx, packages/ui/src/screens/app/__snapshots__/index.test.tsx.snap, packages/ui/src/screens/profile_details/__snapshots__/index.test.tsx.snap, packages/ui/src/screens/transactions/__snapshots__/index.test.tsx.snap, packages/ui/src/screens/transactions/hooks.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/63)
=> feat: add type formatting for transactions lists

apps/web-coreum/package.json, packages/ui/src/components/msg/utils.tsx, packages/ui/src/components/transactions_list/components/desktop/index.tsx, packages/ui/src/components/transactions_list_details/components/list/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/64)
=> feat: comment transactions msg type formatting

apps/web-coreum/package.json, apps/web-coreum/public/locales/en/transactions.json, apps/web-coreum/src/graphql/general/transactions.graphql, apps/web-coreum/src/graphql/types/general_types.ts, packages/ui/declarations.d.ts, packages/ui/src/components/single_transaction_mobile/__snapshots__/index.test.tsx.snap, packages/ui/src/components/single_transaction_mobile/index.tsx, packages/ui/src/components/transactions_list/components/desktop/index.tsx, packages/ui/src/components/transactions_list/components/desktop/utils.tsx, packages/ui/src/components/transactions_list/components/mobile/index.tsx, packages/ui/src/components/transactions_list/index.test.tsx, packages/ui/src/components/transactions_list_details/components/list/components/single_transaction/__snapshots__/index.test.tsx.snap, packages/ui/src/components/transactions_list_details/components/list/components/single_transaction/index.tsx, packages/ui/src/components/transactions_list_details/components/list/index.tsx, packages/ui/src/graphql/general/transactions.graphql, packages/ui/src/graphql/types/general_types.ts, packages/ui/src/screens/transaction_details/components/messages/__snapshots__/index.test.tsx.snap, packages/ui/src/screens/transaction_details/components/overview/index.tsx, packages/ui/src/screens/transaction_details/types.ts, packages/ui/src/screens/transactions/__snapshots__/index.test.tsx.snap, packages/ui/src/screens/transactions/hooks.ts, packages/ui/src/screens/transactions/index.test.tsx, packages/ui/src/screens/transactions/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/66)
=> feat: add additional fields to transactions list

apps/web-coreum/package.json, apps/web-coreum/src/graphql/types/general_types.ts, apps/web/src/graphql/general/messages_by_address.graphql, apps/web/src/graphql/types/general_types.ts, packages/ui/src/components/transactions_list/components/desktop/index.tsx, packages/ui/src/graphql/general/messages_by_address.graphql, packages/ui/src/graphql/types/general_types.ts, packages/ui/src/screens/account_details/components/transactions/hooks.ts, packages/ui/src/screens/transactions/hooks.ts, packages/ui/src/screens/validator_details/components/transactions/hooks.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/67)
=> fix: update transactions list for account and validator transactions tables

apps/web-coreum/package.json, packages/ui/src/utils/convert_msg_type/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/71)
=> feat: update types for NFT transactions

apps/web-coreum/package.json, packages/ui/src/components/layout/__snapshots__/index.test.tsx.snap, packages/ui/src/components/layout/index.tsx, packages/ui/src/components/layout/styles.ts, packages/ui/src/components/layout/types.ts, packages/ui/src/components/transactions_list/__snapshots__/index.test.tsx.snap, packages/ui/src/components/transactions_list/components/mobile/index.tsx, packages/ui/src/components/transactions_list/index.tsx, packages/ui/src/screens/transactions/__snapshots__/index.test.tsx.snap, packages/ui/src/screens/transactions/index.tsx, packages/ui/src/screens/transactions/styles.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/72)
=> fix: update transaction list responsive design

apps/web-coreum/package.json, packages/ui/src/screens/transactions/__snapshots__/index.test.tsx.snap, packages/ui/src/screens/transactions/styles.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/73)
=> fix: update footer position in transactions list page

.github/workflows/build.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/75)
=> feat: update ci

apps/web-coreum/package.json, apps/web-coreum/public/locales/en/message_contents.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/76)
=> fix: update message content for msgNftRemoveFromWhitelist

packages/ui/src/screens/proposal_details/components/votes_graph/hooks.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/77)
=> fix: use correct params for proposal quorum

apps/web-coreum/src/chain.json, packages/ui/src/chain.json, packages/ui/src/chainConfigBackup.json, packages/ui/src/screens/account_details/components/balance/index.tsx, packages/ui/src/screens/account_details/components/transactions/index.tsx, packages/ui/src/screens/account_details/hooks.ts, packages/ui/src/screens/account_details/index.tsx, packages/ui/src/screens/account_details/types.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/78)
=> feat: update token price fetching to use token_price table's value from bdjuno

packages/ui/src/screens/home/components/hero/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/79)
=> fix: update rendering rules for online voting power

.pnp.cjs, apps/web-coreum/package.json, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/82)
=> feat: upgrade version of next

apps/web-coreum/package.json, packages/ui/src/recoil/market/hooks.ts, packages/ui/src/screens/assets/hooks.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/83)
=> feat: update version

apps/web-coreum/package.json, apps/web-coreum/public/locales/en/assets.json, packages/ui/src/screens/asset_details/components/AssetOverview/index.tsx, packages/ui/src/screens/asset_details/components/AssetOverview/styles.ts, packages/ui/src/screens/asset_ibc_details/components/AssetOverview/index.tsx, packages/ui/src/screens/asset_ibc_details/components/AssetOverview/styles.ts, packages/ui/src/screens/assets/components/list/components/desktop/index.tsx, packages/ui/src/screens/assets/components/list/components/mobile/component/single_asset/index.tsx, packages/ui/src/screens/assets/components/list/components/tabs/index.tsx, packages/ui/src/screens/assets/components/list/styles.ts, packages/ui/src/screens/assets/index.tsx, packages/ui/src/screens/assets/styles.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/84)
=> fix: update assets screen ui

apps/web-coreum/package.json, packages/ui/src/screens/transactions/hooks.ts, packages/ui/src/screens/transactions/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/85)
=> fix: update the way of processing transactions

apps/web-coreum/package.json, packages/ui/src/screens/proposal_details/components/overview/index.tsx, packages/ui/src/screens/proposal_details/types.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/86)
=> feat: add height to the proposal details page

apps/web-coreum/package.json, packages/ui/src/screens/params/utils.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/87)
=> feat: remove base_proposal_reward and bonus_proposal_reward

apps/web-coreum/package.json, packages/ui/src/screens/proposal_details/components/overview/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/88)
=> feat: add name to the proposal details page

apps/web-coreum/package.json, apps/web-osmosis/src/screens/account_details/hooks.ts, packages/ui/src/components/nav/components/search_bar/hooks.ts, packages/ui/src/recoil/validators/selectors.ts, packages/ui/src/screens/account_details/hooks.ts, packages/ui/src/screens/account_details/utils.tsx, packages/ui/src/screens/assets/hooks.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/89)
=> fix: optimize and simplify the search function, add ability to search assets by partial includes, update account's state handling

apps/web-coreum/package.json, packages/ui/src/components/msg/asset/burn/index.tsx, packages/ui/src/components/msg/asset/freeze/index.tsx, packages/ui/src/components/msg/asset/mint/index.tsx, packages/ui/src/components/msg/asset/set_whitelisted_limit/index.tsx, packages/ui/src/components/msg/asset/unfreeze/index.tsx, packages/ui/src/components/msg/bank/multisend/index.test.tsx, packages/ui/src/components/msg/bank/multisend/index.tsx, packages/ui/src/components/msg/bank/send/index.test.tsx, packages/ui/src/components/msg/bank/send/index.tsx, packages/ui/src/components/msg/distribution/fund/index.test.tsx, packages/ui/src/components/msg/distribution/fund/index.tsx, packages/ui/src/components/msg/governance/deposit_proposal/index.test.tsx, packages/ui/src/components/msg/governance/deposit_proposal/index.tsx, packages/ui/src/components/msg/staking/delegate/index.test.tsx, packages/ui/src/components/msg/staking/delegate/index.tsx, packages/ui/src/components/msg/staking/redelegate/index.test.tsx, packages/ui/src/components/msg/staking/redelegate/index.tsx, packages/ui/src/components/msg/staking/undelegate/index.test.tsx, packages/ui/src/components/msg/staking/undelegate/index.tsx, packages/ui/src/components/msg/utils.tsx, packages/ui/src/screens/account_details/components/other_tokens/components/desktop/index.tsx, packages/ui/src/screens/account_details/components/other_tokens/components/mobile/index.tsx, packages/ui/src/screens/transaction_details/__snapshots__/index.test.tsx.snap, packages/ui/src/screens/transaction_details/components/messages/index.test.tsx, packages/ui/src/screens/transaction_details/components/messages/index.tsx, packages/ui/src/screens/transaction_details/hooks.ts, packages/ui/src/screens/transaction_details/index.tsx, packages/ui/src/screens/transaction_details/types.ts, packages/ui/src/utils/format_token/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/90)
=> feat: update messages in tx details, update formatNumberWithThousandsSeparator function

packages/ui/src/components/msg/asset/burn/index.tsx, packages/ui/src/components/msg/asset/freeze/index.tsx, packages/ui/src/components/msg/asset/mint/index.tsx, packages/ui/src/components/msg/asset/set_whitelisted_limit/index.tsx, packages/ui/src/components/msg/asset/unfreeze/index.tsx, packages/ui/src/components/msg/ibc_transfer/transfer/index.tsx, packages/ui/src/components/msg/staking/delegate/index.tsx, packages/ui/src/components/msg/staking/redelegate/index.tsx, packages/ui/src/components/msg/staking/undelegate/index.tsx, packages/ui/src/screens/account_details/hooks.ts, packages/ui/src/screens/asset_details/components/AssetOverview/index.tsx, packages/ui/src/screens/asset_details/hooks.ts, packages/ui/src/screens/asset_ibc_details/hooks.ts, packages/ui/src/screens/assets/hooks.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/91)
=> feat: add support of xrpl assets

apps/web-coreum/src/chain.json, packages/ui/src/chainConfig/types.ts, packages/ui/src/components/single_bridge_transaction_mobile/index.tsx, packages/ui/src/components/single_bridge_transaction_mobile/styles.ts, packages/ui/src/components/transactions_list_bridge/components/desktop/index.tsx, packages/ui/src/components/transactions_list_bridge/components/desktop/styles.ts, packages/ui/src/components/transactions_list_bridge/components/mobile/index.tsx, packages/ui/src/components/transactions_list_bridge_details/components/list/components/single_transaction/index.tsx, packages/ui/src/components/transactions_list_bridge_details/components/list/components/single_transaction/styles.ts, packages/ui/src/components/transactions_list_bridge_details/components/list/index.tsx, packages/ui/src/screens/transactions/hooks.ts, packages/ui/src/utils/go_to_page/index.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/94)
=> feat: handle xrpl explorer links, update styles for table cells in bridge tx history

packages/ui/src/screens/transactions/hooks.ts, packages/ui/src/screens/transactions/types.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/95)
=> feat: optimize page loading for bridge tx history

packages/ui/src/components/transactions_list_bridge/components/desktop/index.tsx, packages/ui/src/components/transactions_list_bridge/components/mobile/index.tsx, packages/ui/src/components/transactions_list_bridge_details/components/list/index.tsx, packages/ui/src/screens/transactions/hooks.ts, packages/ui/src/screens/transactions/styles.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/96)
=> feat: add formatting of token and denoms

apps/web-coreum/package.json, apps/web-coreum/src/graphql/types/general_types.ts, packages/ui/src/graphql/types/general_types.ts, packages/ui/src/recoil/validators/hooks.ts, packages/ui/src/screens/proposals/components/list/index.tsx, packages/ui/src/screens/validators/components/list/hooks.ts, packages/ui/src/screens/validators/components/list/types.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/97)
=> feat: update queries for validators to handle all validators

apps/web-coreum/package.json, apps/web-coreum/public/locales/en/transactions.json, packages/ui/src/components/transactions_list_bridge/components/desktop/index.tsx, packages/ui/src/components/transactions_list_bridge/components/desktop/styles.ts, packages/ui/src/components/transactions_list_bridge/components/desktop/utils.tsx, packages/ui/src/components/transactions_list_bridge/components/mobile/index.tsx, packages/ui/src/components/transactions_list_bridge/components/mobile/styles.ts, packages/ui/src/components/transactions_list_bridge_details/components/list/index.tsx, packages/ui/src/components/transactions_list_bridge_details/components/list/styles.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/99)
=> feat: update formatting for amounts, add view on explorer links

packages/ui/src/components/single_proposal/utils.tsx
Closes: #XXXX
---
I have...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/101)
=> fix: fix proposal status color

.github/workflows/build.yml, apps/web-coreum/package.json
Closes: #XXXX
---
I have...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/103)
=> Feature: add automatic version bump to repo

.github/workflows/build.yml
Closes: #XXXX
---
I have...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/104)
=> Fix version bump & install standard version package

.github/workflows/build.yml
Closes: #XXXX
---
I have...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/105)
=> Fix: read tag from coreum app folder

.github/workflows/build.yml
Closes: #XXXX
---
I have...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/106)
=> Fix: Remove patch from standard version

packages/ui/src/components/avatar_name/index.tsx, packages/ui/src/screens/transactions/styles.ts, packages/ui/src/screens/validator_details/components/blocks/index.tsx, packages/ui/src/screens/validator_details/components/blocks/styles.ts, packages/ui/src/screens/validator_details/components/transactions/styles.ts, packages/ui/src/screens/validator_details/components/voting_power/styles.ts, packages/ui/src/screens/validator_details/styles.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/big-dipper-2.0-cosmos/107)
=> fix: update styles for validator's details page
